In [1]:
import numpy as np

## array

### iterable 에서 array 만들기

In [2]:
sample = np.array(
[[0.7, 0.3],
 [0.5, 0.5]]
)

## ndarray

### ndarray 로 특정 shape array 만들기

In [3]:
np.ndarray(shape=(2,2), dtype=float, order='C')

array([[4.65390455e-310, 4.65390441e-310],
       [6.90603530e-310, 0.00000000e+000]])

### ndarray 로 c-style 과 fortran-style array 만들기

In [10]:
np.ndarray(shape=(2,2), dtype=float, order='C')

array([[4.65390455e-310, 4.65390441e-310],
       [6.90603530e-310, 0.00000000e+000]])

In [11]:
np.ndarray(shape=(2,2), dtype=float, order='F')

array([[4.65390455e-310, 6.90603530e-310],
       [4.65390441e-310, 0.00000000e+000]])

### buffer array 를 이용해서 ndarray 만들기

In [19]:
np.ndarray((2,), buffer=np.array([1,2,3]),
                dtype=int) 

array([1, 2])

In [27]:
np.ndarray(shape=(2,), buffer=np.array([1,2,3]),
                dtype=int) 

array([1, 2])

In [26]:
np.ndarray(shape=(2,3), buffer=np.array([[1,2,3], [5,5,5], [2,2,2]]),
                dtype=int) 

array([[1, 2, 3],
       [5, 5, 5]])

In [20]:
np.ndarray((2,), buffer=np.array([1,2,3]),
                offset=8,
                dtype=int) 

array([2, 3])

In [21]:
np.ndarray((2,), buffer=np.array([1,2,3]),
                offset=np.int_().itemsize,
                dtype=int) 

array([2, 3])

## frombuffer

### bytes buffer 에서 bytes array 만들기

In [13]:
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

### count 는 의미 있을 수 있다

In [16]:
np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8)

array([1, 2, 3, 4, 5], dtype=uint8)

In [15]:
np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8, count=3)

array([1, 2, 3], dtype=uint8)