In [1]:
import numpy as np

## searchsorted

[설명](https://wikidocs.net/14597)
- 이미 정렬되어 있는 배열을 대상으로 탐색할 때는 이진탐색(binary search)를 사용하면 계산효율을 대폭 높일 수 있다. 
- Numpy는 `np.searchsorted(array,value,side='left')`를 통해 이진탐색을 수행할 수 있다. 
- side 인자로는 'left'와 'right'가 가능하다. `side='left'`는 `array[i-1] < value <= array[i]`이고, `side='right'`는 `array[i-1] <= value < array[i]`이다. 
- 영역을 벗어나는 경우도 있기 때문에 다음 그림을 참조하는 것이 이해하기 쉽다.



![searchsorted](https://wikidocs.net/images/page/14597/11.png)

### `3` 은 2번째에서 발견된다.

In [2]:
np.searchsorted([1,2,3,4,5], 3)

2

### `5` 를 찾을 때, `side='left'` 로 찾든 `side='right'` 로 찾든 1번에서 발견된다.

In [7]:
x = np.array([0.,13.,26.,30.])

print(x)
print(-1,':',np.searchsorted(x,-1.),',',np.searchsorted(x,-1.,side='right'))
print( 0,':',np.searchsorted(x, 0.),',',np.searchsorted(x, 0.,side='right'))
print( 5,':',np.searchsorted(x, 5.),',',np.searchsorted(x, 5.,side='right'))
print(13,':',np.searchsorted(x,13.),',',np.searchsorted(x,13.,side='right'))
print(15,':',np.searchsorted(x,15.),',',np.searchsorted(x,15.,side='right'))
print(30,':',np.searchsorted(x,30.),',',np.searchsorted(x,30.,side='right'))
print(35,':',np.searchsorted(x,35.),',',np.searchsorted(x,35.,side='right'))

[ 0. 13. 26. 30.]
-1 : 0 , 0
0 : 0 , 1
5 : 1 , 1
13 : 1 , 2
15 : 2 , 2
30 : 3 , 4
35 : 4 , 4


## amin

In [3]:
x = np.array([9.1,8.2,2.3,3,3,7.6,5.2])

np.amin(x)

2.3

## argmin

In [4]:
x = np.array([9.1,8.2,2.3,3,3,7.6,5.2])

np.argmin(x)

2

## sort

In [5]:
x = np.array([9.1,8.2,2.3,3,3,7.6,5.2])

np.sort(x)

array([2.3, 3. , 3. , 5.2, 7.6, 8.2, 9.1])

## argsort

In [6]:
x = np.array([9.1,8.2,2.3,3,3,7.6,5.2])

np.argsort(x)

array([2, 3, 4, 6, 5, 1, 0])