In [2]:
import numpy as np

## around
[around](https://docs.scipy.org/doc/numpy/reference/generated/numpy.around.html)

In [2]:
np.around([0.37, 1.64])

array([0., 2.])

### decimals 반올림 할 자리수

In [3]:
np.around([0.37, 1.64], decimals=1)

array([0.4, 1.6])

In [4]:
np.around([0.3733, 1.6485], decimals=2)

array([0.37, 1.65])

### decimals 0

In [6]:
np.around([0.3733, 1.6485], decimals=0)

array([0., 2.])

### decimals 음수

In [7]:
np.around([221.3733, 77.6485], decimals=-1)

array([220.,  80.])

In [8]:
np.around([221.3733, 77.6485], decimals=-2)

array([200., 100.])

### around === round : True

# condition
https://nov19.tistory.com/106

## all
np.all(조건) - 배열의 모든 데이터가 조건과 맞으면 True 하나라도 다르면 False

## any
np.any(조건) - 배열의 데이터 중 조건과 맞는 데이터가 있으면 True 전혀 없으면 False

## where
np.where(조건, True 일 때 출력값, False 일 때 출력값)

## isnan
np.isnan(arr) - 배열의 데이터 중 NaN 값인 요소는 True 아니면 False로 변환

## isfinite
np.isfinite(arr) - 배열의 데이터 중 셀수 있는 데이터를 True 아니면 False로 변환

## argmax
np.argmax(arr) - 배열의 데이터 중 최대값의 인덱스를 반환

## argmin
np.argmin(arr) - 배열의 데이터 중 최소값의 인덱스를 반환


# filesystem

## dumps and loads
Returns the pickle of the array as a string. pickle.loads or numpy.loads will convert the string back to an array.

In [3]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
d = a.dumps()
d

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02K\x02\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X \x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [6]:
np.loads(d)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  """Entry point for launching an IPython kernel.


array([[1, 2],
       [3, 4]])

In [7]:
import pickle
pickle.loads(d)

array([[1, 2],
       [3, 4]])

## dump and load
signature
- `ndarray.dump(file)`

# linear algebra

## dot

signature
- `ndarray.dot(b, out=None)`

## diagonal
signature 
- `ndarray.diagonal(offset=0, axis1=0, axis2=1)`

## sum

### cumsum
https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.cumsum.html

## product

### cumprod
https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.cumprod.html