In [1]:
import numpy as np

## concatenate

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## stack

In [9]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b), axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

## tile

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.tile(a, 2)

print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]


## indexing
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html