In [2]:
import numpy as np

## concatenate

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## stack
- `stack` : Join a sequence of arrays along a *new axis*.

- `vstack` : Stack arrays in sequence *vertically* (row wise). along first axis.

- `hstack` : Stack arrays in sequence *horizontally* (column wise). along second axis.

- `dstack` : Stack arrays in sequence *depth wise* (along **third dimension**). along third axis.


### stack : along a new axis

In [9]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b), axis=0) # vertically

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b), axis=1) # horizontally

array([[1, 2],
       [2, 3],
       [3, 4]])

### vstack : stack vertically, along first axis

In [3]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

dimension 이 맞아야 한다

In [5]:
a = np.array([1, 2, 3])
b = np.array([100])
np.vstack((a, b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

dimension 1 에서 `[1,2,3]` , `[[1,2,3]]` 둘 다 size 3 이다

In [7]:
a = np.array([[1, 2, 3]])
b = np.array([100])
np.vstack((a, b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [10]:
a = np.array([1, 2, 3])
b = np.array([[20, 30, 40],
              [21, 31, 41]])
np.vstack((a, b))

array([[ 1,  2,  3],
       [20, 30, 40],
       [21, 31, 41]])

In [14]:
np.vstack([a,b])

array([[ 1,  2,  3],
       [20, 30, 40],
       [21, 31, 41]])

In [15]:
a = np.random.multivariate_normal([10, 10], [[3, 2], [2, 3]], size=100000)
b = np.random.multivariate_normal([30, 20], [[2, 3], [1, 3]], size=1000)
print(a.shape, b.shape)

(100000, 2) (1000, 2)


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: covariance is not positive-semidefinite.
  


In [16]:
data = np.vstack([a, b])
data.shape

(101000, 2)

### hstack : stack horizontally, along second axis

In [4]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.hstack((a, b))

array([1, 2, 3, 2, 3, 4])

In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40, 50])
np.hstack((a, b))

array([ 1,  2,  3, 10, 20, 30, 40, 50])

In [13]:
a = np.array([1, 2, 3])
b = np.array([[20, 30, 40],
              [21, 31, 41]])
np.hstack((a, b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### dstack : depthwise, along third axis
#### shape 을 보고, 그에 따라 처리한다

- axis 개수가 3보다 **작으면**, 
    - third axis 는 마지막 axis 이고
    - third axis 는 0 dimension 이고, 추가 될 때 1의 양으로 추가된다
- axis 개수가 3보다 **같거나 크면**,
    - third axis 는 앞에서부터 세서 3번째 axis 이다.

axis 개수가 3보다 작은 경우

In [78]:
a = np.array((1,2,3))
b = np.array((2,3,4))
(a.shape, b.shape) # (1x3x0, 1x3x0) 으로 생각하면 third axis 로 이해할 수 있다

((3,), (3,))

In [21]:
res = np.dstack((a,b))
res

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [22]:
res.shape

(1, 3, 2)

마찬가지로 shape 을 따졌을 때, axis 개수가 3보다 작다.

In [23]:
# first axis, second axis, third axis 를 따질 때, 뒤에서부터 따진다. 
# 마지막 0 dimension 을 따지라는 말
a = np.array([[1],[2],[3]]) # 즉, 1x3x1x0 로 보라는 말
b = np.array([[2],[3],[4]])
(a.shape, b.shape) # 뒤에서부터 따지면, (3x1x1, 3x1x1)

((3, 1), (3, 1))

In [24]:
res = np.dstack((a,b))
res

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [25]:
res.shape

(3, 1, 2)

shape 을 따졌을 때, axis 개수가 3 이상인 경우

In [80]:
a = np.array([[[1],[2]],[[2],[3]],[[3], [4]]]) # 즉, 3x2x1x0 로 보라는 말
b = np.array([[[1],[2]],[[2],[3]],[[3], [4]]])
(a.shape, b.shape) # 뒤에서부터 따지면, (3x2x1x0, 3x2x1x0)

((3, 2, 1), (3, 2, 1))

In [81]:
res = np.dstack((a,b))
res

array([[[1, 1],
        [2, 2]],

       [[2, 2],
        [3, 3]],

       [[3, 3],
        [4, 4]]])

In [82]:
res.shape

(3, 2, 2)

## split
- split : Split an array into multiple sub-arrays as views into ary.
- hsplit : Split array into multiple sub-arrays horizontally (column-wise). second axis
- vsplit : Split array into multiple sub-arrays vertically (row wise). first axis
- dsplit : Split array into multiple sub-arrays along the 3rd axis (depth). third axis
- array_split : Split an array into multiple sub-arrays of equal or near-equal size. Does not raise an exception if an equal division cannot be made.
- list of arrays 를 반환한다는 점을 유의
- `res = split(src)` 일 때 `stack(res) == src` 임을 이해

### split
https://numpy.org/doc/stable/reference/generated/numpy.split.html#numpy.split
```
numpy.split(ary, indices_or_sections, axis=0)
```
- indices_or_sections
    - If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.
    - If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split.
    - 이처럼 몇개로 나눌 것인지 또는 어디에서 어디까지로 나누어 갈 것인지를 명시하는 것

N 개의 array 로 나눈다

In [61]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [63]:
x = np.arange(12.0)
np.split(x, 3)

[array([0., 1., 2., 3.]), array([4., 5., 6., 7.]), array([ 8.,  9., 10., 11.])]

`[idx_i, idx_i+1, ...]` 이면, `array[idx_{i}:idx_{i+1}]` 식으로 나누어 나간다.

In [62]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

### vsplit : vertically, row wise, first axis

In [65]:
x = np.arange(16.0).reshape(4, 4)
x.shape

(4, 4)

In [71]:
res = np.vsplit(x, 2)
print(len(res))
for arr in res:
    print(arr.shape)

2
(2, 4)
(2, 4)


In [73]:
res = np.vsplit(x, np.array([3, 6]))
print(len(res))
for arr in res:
    print(arr.shape) 
# [:3] 의 first axis 에 대해 한번
# [3:6] 의 first axis 에 대해 한번
# [6:] 의 first axis 에 대해 한번

3
(3, 4)
(1, 4)
(0, 4)


In [109]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [110]:
res = np.vsplit(x, 2)
print(len(res))
for arr in res:
    print(arr.shape)

2
(1, 2, 2)
(1, 2, 2)


In [112]:
np.vstack(res)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [111]:
x == np.vstack(res)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

### hsplit

In [84]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [86]:
res = np.hsplit(x, 2)
print(len(res))
for arr in res:
    print(arr.shape)

2
(4, 2)
(4, 2)


In [87]:
res = np.hsplit(x, [3,6])
print(len(res))
for arr in res:
    print(arr.shape)

3
(4, 3)
(4, 1)
(4, 0)


In [88]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [104]:
res = np.hsplit(x, 2)
print(len(res))
for arr in res:
    print(arr.shape)

2
(2, 1, 4)
(2, 1, 4)


In [105]:
np.hstack(res)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

### dsplit

In [91]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [92]:
res = np.dsplit(x, 2)
print(len(res))
for arr in res:
    print(arr.shape)

2
(2, 2, 2)
(2, 2, 2)


In [99]:
res = np.dsplit(x, [3,6])
print(len(res))
for arr in res:
    print(arr)
    print(arr.shape)

3
[[[ 0.  1.  2.]
  [ 4.  5.  6.]]

 [[ 8.  9. 10.]
  [12. 13. 14.]]]
(2, 2, 3)
[[[ 3.]
  [ 7.]]

 [[11.]
  [15.]]]
(2, 2, 1)
[]
(2, 2, 0)


In [102]:
np.dstack(res)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

### array_split
- split 과 같다.
- 하나의 차이는 equally divide 되지 않는 것들을 처리 할 수 있다는 점

In [115]:
x = np.arange(8.0)

In [116]:
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [117]:
np.split(x,3)

ValueError: array split does not result in an equal division

In [114]:
x = np.arange(7.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

## block
Assemble an nd-array from nested lists of blocks.


In [26]:
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([
    [A,               np.zeros((2, 3))],
    [np.ones((3, 2)), B               ]
])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

With a list of depth 1, block can be used as hstack

In [27]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.block([a, b, 10])  

array([ 1,  2,  3,  2,  3,  4, 10])

With a list of depth 2, block can be used in place of vstack:

In [28]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.block([[a], [b]]) 

array([[1, 2, 3],
       [2, 3, 4]])

In [30]:
A = np.ones((2, 2), int)
B = 2 * A
(A.shape, B.shape)

((2, 2), (2, 2))

In [32]:
res = np.block([[A], [B]])  
res

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [33]:
res.shape

(4, 2)

## tile

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.tile(a, 2)

print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]


## where
[reference](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)
```
np.where(condition, x, y)
```

In [13]:
a = np.arange(10)
print(a)
res = np.where(a < 5, a, 10*a)
print(res)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


## atleast
- atleast_1d : https://numpy.org/doc/stable/reference/generated/numpy.atleast_1d.html#numpy.atleast_1d
- atleast_2d : https://numpy.org/doc/stable/reference/generated/numpy.atleast_2d.html#numpy.atleast_2d
- atleast_3d : https://numpy.org/doc/stable/reference/generated/numpy.atleast_3d.html#numpy.atleast_3d

### atleast_1d
```
numpy.atleast_1d(*arys)
```

In [34]:
np.atleast_1d(1.0)

array([1.])

In [35]:
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [36]:
np.atleast_1d(x) is x

True

In [37]:
np.atleast_1d(1, [3, 4])

[array([1]), array([3, 4])]

## atleast_2d
```
numpy.atleast_2d(*arys)
```

In [39]:
np.atleast_2d(3.0)

array([[3.]])

In [43]:
x = np.arange(3.0)
x

array([0., 1., 2.])

In [44]:
np.atleast_2d(x)

array([[0., 1., 2.]])

In [42]:
np.atleast_2d(x).base is x

True

In [46]:
np.atleast_2d(1, [1, 2], [[1, 2]])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]

### np.atleast_3d(3.0)
```
numpy.atleast_3d(*arys)
```

In [48]:
np.atleast_3d(3.0)

array([[[3.]]])

1차원의 경우, first axis 와 third axis 에 dim 1 으로 추가

In [56]:
x = np.arange(3)
x.shape

(3,)

In [50]:
np.atleast_3d(x).shape

(1, 3, 1)

2차원의 경우, third axis 에 dim 1 으로 추가

In [55]:
x = np.arange(12.0).reshape(4,3)
x.shape

(4, 3)

In [54]:
np.atleast_3d(x).shape

(4, 3, 1)

In [58]:
np.atleast_3d(x).base is x.base 

False

In [59]:
np.atleast_3d(x) is x

False

In [60]:
for arr in np.atleast_3d([1, 2], [[1, 2]], [[[1, 2]]]):
    print(arr, arr.shape)

[[[1]
  [2]]] (1, 2, 1)
[[[1]
  [2]]] (1, 2, 1)
[[[1 2]]] (1, 1, 2)


## broadcast
- broadcast_to
- broadcast_arrays

### broadcast_to
https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html

### broadcast_arrays

## indexing
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

# linear algebra

### np.outer
- [reference](https://numpy.org/doc/1.18/reference/generated/numpy.outer.html)
- Given two vectors, `a = [a0, a1, ..., aM]` and `b = [b0, b1, ..., bN]`, the outer product is:
```
[[a0*b0  a0*b1 ... a0*bN ]
 [a1*b0    .
 [ ...          .
 [aM*b0            aM*bN ]]
```

In [163]:
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

An example using a “vector” of letters:

In [164]:
x = np.array(['a', 'b', 'c'], dtype=object)
np.outer(x, [1, 2, 3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

### np.inner
- [reference](https://numpy.org/doc/1.18/reference/generated/numpy.inner.html)
- Inner product of two arrays.
- Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

In [165]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

in higher dimensions a sum product over the last axes.

In [168]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [170]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [171]:
np.inner(a, b)

array([[ 14,  38,  62],
       [ 86, 110, 134]])

# NEXT
- https://numpy.org/doc/1.18/reference/generated/numpy.inner.html
- https://www.slideshare.net/dahlmoon/numpy-20160519